title:              Haohan (Carrie) Zhang
email:              haohanz@andrew.cmu.edu
description:        My heart is in the work.
author:             haohanz
baseurl:            ""
url:                "https://haohanz.github.io"

# Social Profiles
twitter_username:   HAOHANZHANG5
github_username:    haohanz
facebook_username:  100011200443026
linkedin_username:  haohan-zhang

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-144117094-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
